# Generated by Django 3.0.5 on 2020-04-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('excelfile', models.FileField(upload_to='excels')),
            ],
        ),
        migrations.CreateModel(
            name='InputParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=512, verbose_name='模式')),
                ('max_bat', models.FloatField(verbose_name='电池最大容量')),
                ('cur_bat', models.FloatField(verbose_name='电池当前电量')),
                ('charge_bat', models.FloatField(verbose_name='电池充电电量')),
                ('run_bat', models.FloatField(verbose_name='电池放电电量')),
                ('a_laden', models.TimeField(verbose_name='充电开始时间')),
                ('e_laden', models.TimeField(verbose_name='充电结束')),
                ('a_entladen', models.TimeField(verbose_name='放电开始')),
                ('e_entladen', models.TimeField(verbose_name='放电结束')),
                ('percent_power', models.FloatField(default=100, verbose_name='供电百分比')),
                ('netzentlastang', models.FloatField(default=100, verbose_name='缓解变量')),
            ],
        ),
    ]
